<a href="https://colab.research.google.com/github/Lukedzc/Bootcamp-ML/blob/main/Regresja_liniowa_r%C3%B3wnanie_normalne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Import bibliotek

import numpy as np

In [4]:
#Przygotowanie danych

X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [5]:

X1 = X1.reshape(m, 1) #zmiana rozmiaru danych: 6 wierszy, jedna kolumna
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [6]:
bias = np.ones((m, 1)) #generujemy wektor wyrazów wolnych; tzw bias (bajas)
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [8]:

X = np.append(bias, X1, axis=1) #dodajemy do naszej zmiennej
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


Regresja liniowa w $R^2$:
$$Y = w_0 + w_1X_1$$
$$Y = W^TX$$
gdzie: $$W= \left[\begin{matrix}w_0\\w_1\end{matrix}\right]$$ $$ X= \left[\begin{matrix}1\\X_1\end{matrix}\right] $$ stąd $$ W^T= \left[\begin{matrix}w_0&w_1\end{matrix}\right] $$    
$$Y = W^TX = \left[\begin{matrix}w_0&w_1\end{matrix}\right] \cdot  \left[\begin{matrix}1\\X_1\end{matrix}\right] = w_0 + w_1X_1$$

Równanie normalne - równanie pozwalające obliczyć minimum funkcji straty (o ile istnieje)
$$W = (X^TX)^{-1}(X^TY)$$

In [9]:

np.dot(X.T, X) #(X transp. * X)

array([[ 6., 21.],
       [21., 91.]])


L = np.linalg.inv(np.dot(X.T, X)) - odwracamy powyższe równanie i przypisujemy do L;
L

In [10]:

L = np.linalg.inv(np.dot(X.T, X))
L

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [11]:
# obliczamy drygą macież, przypisujemy do P, jako prawa strona (X transpon. * Y)
P = np.dot(X.T, Y)
P

array([21750., 80500.])

In [12]:
# mnożymy L *P = otrzymujemy macierz wag, postać naszego modelu liniowego; W0 - 2750, W1 - 250
np.dot(L, P)

array([2750.,  250.])

Końcowa postać modelu$$Y = 2750 + 250X_1$$

Regresja liniowa przy pomocy scikit-learn
(powyżej natomiast obliczenie regresji liniowej w oparciu o równanie normalne)




In [13]:

from sklearn.linear_model import LinearRegression

regression = LinearRegression() #tworzymy instancję klasy
regression.fit(X1, Y) #użyć metody fit; w metodzie fit przekazujemy tylko cechy (bez jedynek)

print(regression.intercept_) # współczynnik W0 - miejsce przecięcia z osią Y
print(regression.coef_[0])

2750.0
250.0
